// Mock data shaped like the Google Places API (New) "Place" object,
// so the real API can later be swapped in without changing the UI code.
// Reference fields: displayName, types, priceLevel, rating, location,
// dineIn, takeout.
export const mockRestaurants = [
  {
    id: "mock-001",
    displayName: { text: "Luna's Trattoria", languageCode: "en" },
    types: ["italian_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.5,
    location: { latitude: 30.2711, longitude: -97.7437 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-002",
    displayName: { text: "Golden Dragon", languageCode: "en" },
    types: ["chinese_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    rating: 4.2,
    location: { latitude: 30.2755, longitude: -97.7404 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-003",
    displayName: { text: "El Asador", languageCode: "en" },
    types: ["mexican_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    rating: 4.6,
    location: { latitude: 30.2682, longitude: -97.7468 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-004",
    displayName: { text: "Sakura Sushi Bar", languageCode: "en" },
    types: ["sushi_restaurant", "japanese_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    rating: 4.7,
    location: { latitude: 30.2729, longitude: -97.7391 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-005",
    displayName: { text: "The Burger Yard", languageCode: "en" },
    types: ["hamburger_restaurant", "american_restaurant"],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    rating: 4.0,
    location: { latitude: 30.2698, longitude: -97.7512 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-006",
    displayName: { text: "Bombay Spice House", languageCode: "en" },
    types: ["indian_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.4,
    location: { latitude: 30.2774, longitude: -97.7459 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-007",
    displayName: { text: "Le Petit Bistro", languageCode: "en" },
    types: ["french_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_VERY_EXPENSIVE",
    rating: 4.8,
    location: { latitude: 30.2645, longitude: -97.7388 },
    dineIn: true,
    takeout: false,
  },
  {
    id: "mock-008",
    displayName: { text: "Seoul Garden BBQ", languageCode: "en" },
    types: ["korean_restaurant", "barbecue_restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.5,
    location: { latitude: 30.2806, longitude: -97.7432 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-009",
    displayName: { text: "Mediterraneo Grill", languageCode: "en" },
    types: ["mediterranean_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.3,
    location: { latitude: 30.2667, longitude: -97.7501 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-010",
    displayName: { text: "Pho Real", languageCode: "en" },
    types: ["vietnamese_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    rating: 4.6,
    location: { latitude: 30.2789, longitude: -97.7375 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-011",
    displayName: { text: "The Smoking Rib", languageCode: "en" },
    types: ["barbecue_restaurant", "american_restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.7,
    location: { latitude: 30.2719, longitude: -97.7448 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-012",
    displayName: { text: "Casa de Tapas", languageCode: "en" },
    types: ["spanish_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    rating: 4.4,
    location: { latitude: 30.2734, longitude: -97.7359 },
    dineIn: true,
    takeout: false,
  },
  {
    id: "mock-013",
    displayName: { text: "Green Leaf Vegan Kitchen", languageCode: "en" },
    types: ["vegan_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.5,
    location: { latitude: 30.2658, longitude: -97.7423 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-014",
    displayName: { text: "Athens Taverna", languageCode: "en" },
    types: ["greek_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.2,
    location: { latitude: 30.2812, longitude: -97.7397 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-015",
    displayName: { text: "Coastal Crab Shack", languageCode: "en" },
    types: ["seafood_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    rating: 4.6,
    location: { latitude: 30.2691, longitude: -97.7484 },
    dineIn: true,
    takeout: false,
  },
  {
    id: "mock-016",
    displayName: { text: "Pizza Nonna", languageCode: "en" },
    types: ["pizza_restaurant", "italian_restaurant"],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    rating: 4.3,
    location: { latitude: 30.2743, longitude: -97.7415 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-017",
    displayName: { text: "Thai Orchid", languageCode: "en" },
    types: ["thai_restaurant", "restaurant"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    rating: 4.5,
    location: { latitude: 30.2625, longitude: -97.7441 },
    dineIn: true,
    takeout: true,
  },
  {
    id: "mock-018",
    displayName: { text: "The Velvet Steakhouse", languageCode: "en" },
    types: ["steak_house", "american_restaurant"],
    priceLevel: "PRICE_LEVEL_VERY_EXPENSIVE",
    rating: 4.9,
    location: { latitude: 30.2761, longitude: -97.7468 },
    dineIn: true,
    takeout: false,
  },
];
